version: "3.9"
services:
  database-postgres:
    image: postgres:latest
    container_name: database-postgres
    hostname: localhost
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: controlcopies
    volumes:
      - database-postgres:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    container_name: control_copies_next13
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app
    ports:
      - '3340:3340'
    depends_on:
      - database-postgres
volumes:
  database-postgres: