'use client'
import { Header } from '@/components/Header'
import { GlobalStyle } from '@/styles/global'
import { theme } from '@/styles/theme'
import { ReactNode } from 'react'
import { ThemeProvider } from 'styled-components'
import { Toaster } from 'react-hot-toast'
import { Container } from './styles'

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <GlobalStyle />
          <Header />
          <Toaster />

          <Container>{children}</Container>
        </ThemeProvider>
      </body>
    </html>
  )
}
