"use client"
import { GlobalStyle } from "@/styles/global"
import { theme } from "@/styles/theme"
import { ThemeProvider } from "styled-components"

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <GlobalStyle />

          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
